// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RandomApp.ProductManagement.Infrastructure.DataAccess;

#nullable disable

namespace ProductManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20241116091128_moreProducts")]
    partial class moreProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Random.App.ProductManagement.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Sugar Free Drink",
                            Name = "Coca Cola Zero"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sugar Free Drink",
                            Name = "Coca Cola Light"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Chocholate Bar",
                            Name = "Snickers"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Chocholate Bar",
                            Name = "Mars"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Chocholate Bar",
                            Name = "Kinder Bueno"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
